[package]
name = "godot-codegen"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"
license = "MPL-2.0"
keywords = ["gamedev", "godot", "engine", "codegen"]
categories = ["game-engines", "graphics"]

[features]
codegen-fmt = []
codegen-full = []
double-precision = []

[dependencies]
quote = "1"
proc-macro2 = "1"
which = "4"
heck = "0.4"

# Version >= 1.5.5 for security: https://blog.rust-lang.org/2022/03/08/cve-2022-24713.html
# 'unicode-gencat' needed for \d, see: https://docs.rs/regex/1.5.5/regex/#unicode-features
regex = { version = "1.5.5", default-features = false, features = ["std", "unicode-gencat"] }
nanoserde = "0.1.29"
