[package]
name = "dodge-the-creeps"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { path = "../../../godot", default-features = false, features = ["formatted"] }
rand = "0.8"
