[package]
name = "godot-ffi"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"
license = "MPL-2.0"
keywords = ["gamedev", "godot", "engine", "ffi"]
categories = ["game-engines", "graphics"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/ref