# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: godot
description: "Run Godot integration tests"

inputs:
  artifact-name:
    required: true
    description: "Name of the compiled Godot artifact to download"

  godot-binary:
    required: true
    description: "Filename of the Godot executable"

  godot-args:
    required: false
    default: ''
    description: "Command-line arguments passed to Godot"

  rust-toolchain:
    required: false
    default: 'stable'
    description: "Rust toolchain specifier (e.g. 'nightly')"

  rust-extra-args:
    required: false
    default: ''
    description: "Extra command line arguments for 'cargo build', e.g. features"

  rust-env-rustflags:
    required: false
    default: ''
    description: "Extra values for the RUSTFLAGS env var"

  with-llvm:
    required: false
    default: ''
    description: "Set to 'true' if LLVM should be installed"


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: "Install Godot"
      uses: ./.github/composite/godot-install
      with:
        artifact-name: ${{ inputs.artifact-name }}
        godot-binary: ${{ inputs.godot-binary }}

    # The chmod seems still necessary, although applied before uploading artifact. Possibly modes are not preserved.
    # The `| xargs` pattern trims the output, since printed version may contain extra newline, which causes problems in env vars.
    - name: "Inspect Godot version"
      run: |
        godotVer=$($GODOT4_BIN --version | xargs || true)
        gitSha=$(echo $godotVer | sed -E "s/.+custom_build\.//")
        echo "GODOT_BUILT_FROM=_Built from [\`$godotVer\`](https://github.com/godotengine/godot/commit/$gitSha)._" >> $GITHUB_ENV
      shell: bash

    # Note: if this fails, run `git diff -R > tweaks.patch` after updating the file manually
    - name: "Copy and compare GDExtension header"
      if: inputs.artifact-name == 'godot-linux'
      run: |
        mkdir -p godot-codegen/input
        cp $RUNNER_DIR/godot_bin/gdextension_interface.h godot-codegen/input/gdextension_interface.h
        git apply godot-codegen/input/tweak.patch -v
        git diff --exit-code --quiet || {
            echo "OUTCOME=header-diff" >> $GITHUB_ENV
            echo "gdextension_interface.h is not up-to-date; abort."
            echo ""
            
            echo "### :x: Outdated GDExtension API header" >> $GITHUB_STEP_SUMMARY
            echo "gdextension_interface.h contains the following differences:" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`diff" >> $GITHUB_STEP_SUMMARY
            git diff >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "After manually updating file, run:   \`git diff -R > tweak.patch\`." >> $GITHUB_STEP_SUMMARY

        	exit 1
        }
      shell: bash

    - name: "Install Rust"
      uses: ./.github/composite/rust
      with:
        rust: ${{ inpu