# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: godot
description: "Run Godot integration tests"

inputs:
  artifact-name:
    required: true
    description: "Name of the compiled Godot artifact to download"

  godot-binary:
    required: true
    description: "Filename of the Godot executable"

  godot-args:
    required: false
    default: ''
    description: "Command-line arguments passed to Godot"

  rust-toolchain:
    required: false
    default: 'stable'
    description: "Rust toolchain specifier (e.g. 'nightly')"

  rust-extra-args:
    required: false
    default: ''
    description: "Extra command line arguments for 'cargo build', e.g. features"

  rust-env-rustflags:
    required: false
    default: ''
    description: "Extra values for the RUSTFLAGS env var"

  with-llvm:
    required: false
    default: ''
    description: "Set to 'true' if LLVM should be installed"


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: "Install Godot"
      uses: ./.github/composite/godot-install
      with:
        artifact-name: ${{ inputs.artifact-name }}
        godot-binary: ${{ inputs.godot-binary }}

    # The chmod seems still 